# coding:utf-8
# Public company brochure, linked by the current Wix contact page, pages 17–22.
# Historic customer names, statistics, dates and equipment counts are not reused.
from services import add,SERVICES
PDF='https://www.hipstudio.hu/_files/ugd/b0aee1_357ff796b7a145d28d1f8f021ad884d5.pdf'
start=len(SERVICES)
add('souvenir','emlekfotozas || souvenir-photography || erinnerungsfotografie','Emlékfotózás || Souvenir photography || Erinnerungsfotografie','event','rendezvenyfotozas-budapest','referencia-videók',
'A rendezvény élménye kézzelfogható emlékként is továbbvihető. A fotófalnál készülő portré más feladat, mint az esemény teljes dokumentálása. || An event can leave a tangible memory. A portrait at a photo wall is a different task from documenting the entire event. || Eine Veranstaltung kann eine greifbare Erinnerung hinterlassen. Ein Porträt vor der Fotowand ist eine andere Aufgabe als die vollständige Eventdokumentation.',
'A nyilvános cégbemutató fotófal előtti emlékfotózást és helyszíni képnyomtatást ismertet. A háttér, a várható létszám és az átadási mód közös tervezést igényel. || The public company profile describes photo-wall portraits and on-site printing. Background, expected attendance and delivery method need to be planned together. || Das öffentliche Firmenprofil beschreibt Fotowandporträts und Druck vor Ort. Hintergrund, erwartete Personenzahl und Übergabeform müssen gemeinsam geplant werden.',
'A briefben legyen benne a résztvevők száma, az esemény időtartama és a nyomtatási igény. A nyomat méretét, mennyiségét és az elérhető helyszíni kapacitást külön egyeztetjük. || Include attendance, event duration and printing requirements. Print size, quantity and available on-site capacity are agreed separately. || Nenne Gästezahl, Veranstaltungsdauer und Druckbedarf. Format, Stückzahl und verfügbare Kapazität vor Ort werden gesondert abgestimmt.',
'A nyomtatás automatikusan jár a rendezvényfotózáshoz? || Is printing automatically included in event photography? || Ist der Druck bei Eventfotografie automatisch enthalten?',
'Nem. A helyszíni nyomtatás külön egyeztetett feladat. A cégbemutató referenciája nem minden eseményhez járó csomagígéret. || No. On-site printing is agreed separately. The company profile’s reference is not a package promise for every event. || Nein. Druck vor Ort wird gesondert vereinbart. Die Referenz im Firmenprofil ist keine Paketzusage für jede Veranstaltung.')
add('greenbox','greenbox-fotozas || green-screen-photography || greenscreen-fotografie','Greenbox fotózás || Green-screen photography || Greenscreen-Fotografie','event','rendezvenyfotozas-budapest','referencia-videók',
'Egy rendezvény képi világa saját háttérrel és közösen kitalált jelenettel is megjelenhet. A greenbox fotózás a felvételt utólag összeállított környezethez kapcsolja. || An event’s visual identity can appear through a custom background and a planned scene. Green-screen photography combines a photograph with a composited setting. || Die Bildwelt einer Veranstaltung kann durch einen eigenen Hintergrund und eine geplante Szene sichtbar werden. Greenscreen-Fotografie verbindet die Aufnahme mit einer zusammengesetzten Umgebung.',
'A greenbox fotózás önálló pontként szerepel a HIPStudio nyilvános cégbemutatójában. A háttérterv és a résztvevők megjelenése együtt határozza meg a képek karakterét. || Green-screen photography has its own section in HIPStudio’s public company profile. Background design and participants’ appearance jointly shape the images. || Greenscreen-Fotografie hat einen eigenen Abschnitt im öffentlichen Firmenprofil von HIPStudio. Hintergrundgestaltung und Darstellung der Beteiligten prägen gemeinsam die Bilder.',
'Tisztázzuk a háttéranyag felhasználási jogát, a rendelkezésre álló helyet és a képek átadásának módját. A kompozit képet nem mutatjuk valós dokumentarista helyszínként. || Clarify rights to the background, available space and image delivery. A composite image is not presented as documentary evidence of a real location. || Zu klären sind Hintergrundrechte, Platzbedarf und Bildübergabe. Ein zusammengesetztes Bild wird nicht als dokumentarischer Beleg eines realen Ortes dargestellt.',
'Milyen háttér használható? || What backgrounds can be used? || Welche Hintergründe können verwendet werden?',
'Előre egyeztetett, felhasználható háttéranyag. Védjegyet, más alkotását vagy ügyfélképet csak megfelelő jogosultsággal lehet beépíteni. || A pre-agreed background that may lawfully be used. Trademarks, other people’s work or client imagery require appropriate rights. || Ein vorher abgestimmter, nutzbarer Hintergrund. Marken, fremde Werke oder Kundenbilder benötigen entsprechende Rechte.')
add('streaming','konferencia-streameles || conference-streaming || konferenz-streaming','Konferencia-streamelés || Conference streaming || Konferenz-Streaming','film','rovidfilm-keszites','referencia-videók',
'A helyszíni program a távoli közönséghez is eljuthat. A közvetítésnél a kép mellett a beszéd érthetősége, a program és a hozzáférés módja is meghatározó. || A live programme can reach a remote audience. In a stream, clear speech, programme structure and access arrangements matter alongside the image. || Ein Liveprogramm kann auch ein entferntes Publikum erreichen. Bei einem Stream zählen neben dem Bild verständliche Sprache, Programmstruktur und Zugangsart.',
'A nyilvános cégbemutató konferencia-streamelést és helyszíni élőkép-kivetítést ismertet. A bizalmas események teljes felvételét nem kezeli szabadon bemutatható referenciaként. || The public company profile describes conference streaming and live projection at the venue. It does not treat complete recordings of confidential events as freely shareable references. || Das öffentliche Firmenprofil beschreibt Konferenz-Streaming und Liveprojektion am Veranstaltungsort. Vollständige Aufzeichnungen vertraulicher Veranstaltungen werden nicht als frei vorzeigbare Referenzen behandelt.',
'Az adás célplatformja, a nézők hozzáférése, a helyszíni internet és a hangtechnikai kapcsolódás legyen része az egyeztetésnek. A rögzítésről és utólagos hozzáférésről külön döntés szükséges. || Discuss the platform, viewer access, venue internet and audio connections. Recording and later access require separate decisions. || Plattform, Zuschauerzugang, Internet vor Ort und Audioanbindung gehören zur Abstimmung. Aufzeichnung und spätere Verfügbarkeit erfordern separate Entscheidungen.',
'Nyilvános vagy zárt közvetítés is tervezhető? || Can a stream be public or restricted? || Kann ein Stream öffentlich oder zugangsbeschränkt sein?',
'A hozzáférési igényt és a platform lehetőségeit előre kell egyeztetni. Ellenőrzött technikai terv nélkül nem ígérünk nézőszámot vagy hozzáférési funkciót. || Access requirements and platform capabilities must be discussed in advance. We do not promise audience capacity or access features without a checked technical plan. || Zugangsanforderungen und Plattformmöglichkeiten müssen vorab geklärt werden. Ohne geprüften technischen Plan werden keine Zuschauerzahlen oder Zugriffsfunktionen zugesagt.')
add('sports-video','sportvideo || sports-video || sportvideo','Sportvideó || Sports video || Sportvideo','film','rovidfilm-keszites','referencia-videók',
'A mozdulat, a tempó és az esemény rendje együtt adja a sportfelvétel történetét. A kamerák helyét a történésekhez és a biztonságos hozzáféréshez kell igazítani. || Movement, pace and the event’s structure shape a sports film. Camera positions need to follow the action and safe access arrangements. || Bewegung, Tempo und Veranstaltungsablauf prägen einen Sportfilm. Kamerapositionen müssen zum Geschehen und zum sicheren Zugang passen.',
'A HIPStudio cégbemutatója sportfelvételeket és az ezekből szerkesztett rövid vagy hosszabb filmeket is felsorolja. A felvétel és a hang utómunkája a kívánt végtermékhez igazodik. || HIPStudio’s company profile lists sports recording and short or longer edited films. Footage and sound editing depend on the desired final work. || Das Firmenprofil von HIPStudio nennt Sportaufnahmen und daraus geschnittene kurze oder längere Filme. Bild- und Tonbearbeitung richten sich nach dem gewünschten Ergebnis.',
'Add meg a sportágat, a programot, a mozgás útvonalát és a szervezői hozzáférést. A teljes eseményrögzítés és a hangulati összefoglaló eltérő felvételi tervet igényel. || Specify the sport, schedule, movement routes and organiser access. Full-event recording and a highlights film need different recording plans. || Nenne Sportart, Programm, Bewegungsabläufe und Zugang über den Veranstalter. Vollständige Aufzeichnung und Highlightfilm benötigen unterschiedliche Aufnahmepläne.',
'Összefoglaló vagy teljes rögzítés készüljön? || Should we record highlights or the full event? || Sollen Highlights oder die gesamte Veranstaltung aufgenommen werden?',
'Ezt a felhasználás dönti el. A választást a forgatás előtt kell rögzíteni, mert a teljes eseményhez szükséges folyamatos lefedettség utólag nem pótolható. || Intended use determines the choice. Decide before filming; continuous coverage for a full recording cannot be added afterwards. || Der Verwendungszweck entscheidet. Die Wahl muss vor dem Dreh feststehen, da durchgehende Abdeckung später nicht ergänzt werden kann.')
add('concert-video','koncertvideo || concert-video || konzertvideo','Koncertvideó || Concert video || Konzertvideo','film','rovidfilm-keszites','referencia-videók',
'A koncert képe a hanggal együtt teljes. A színpadi fények, a közönség és az előadás ritmusa közös felvételi és vágási tervet kíván. || Concert imagery works together with sound. Stage lighting, the audience and the performance’s rhythm need a shared recording and editing plan. || Konzertbilder wirken zusammen mit dem Ton. Bühnenlicht, Publikum und Rhythmus der Aufführung brauchen einen gemeinsamen Aufnahme- und Schnittplan.',
'A nyilvános cégbemutató koncertfelvételeket, vágást és hangkeverést ismertet. A teljes előadás és a rövid promóciós anyag célját érdemes már az előkészítéskor szétválasztani. || The public company profile describes concert recording, editing and audio mixing. Distinguish a complete performance from a short promotional film during planning. || Das öffentliche Firmenprofil beschreibt Konzertaufnahmen, Schnitt und Tonmischung. Vollständige Aufführung und kurzer Werbefilm sollten schon bei der Planung unterschieden werden.',
'A setlist, a hangtechnikai csatlakozás, a színpadi hozzáférés és a megjelenési jogosultságok fontos kiindulópontok. A zene felhasználását nem helyettesíti a videó megrendelése. || Set list, audio connections, stage access and publication rights are important starting points. Commissioning a video does not itself secure music usage rights. || Setlist, Audioanschlüsse, Bühnenzugang und Veröffentlichungsrechte sind wichtige Grundlagen. Ein Videoauftrag sichert nicht automatisch Musiknutzungsrechte.',
'A hangfelvétel is része a tervnek? || Is audio recording part of the plan? || Gehört die Tonaufnahme zur Planung?',
'Igen, a kívánt végtermékhez a hangfelvételi forrást és az utómunkát is egyeztetni kell. A konkrét technikai lehetőségeket a helyszínnel együtt tisztázzuk. || Yes. Audio sources and post-production need to be agreed for the desired final film. Technical options are discussed with the venue. || Ja. Tonquellen und Nachbearbeitung müssen zum gewünschten Film abgestimmt werden. Technische Möglichkeiten werden mit dem Veranstaltungsort geklärt.')
add('music-video','videoklip || music-videos || musikvideos','Videoklip || Music videos || Musikvideos','film','rovidfilm-keszites','referencia-videók',
'Egy dal képi világa saját történetet mesélhet. A videoklipnél az előadó karaktere, a zene ritmusa és a koncepció együtt vezeti a forgatást. || A song’s visual world can tell its own story. In a music video, the performer’s character, musical rhythm and concept guide the shoot together. || Die Bildwelt eines Songs kann eine eigene Geschichte erzählen. Bei einem Musikvideo leiten Künstlerpersönlichkeit, Rhythmus und Konzept gemeinsam den Dreh.',
'A HIPStudio filmoldala és cégbemutatója is említi a videoklipkészítést. A szereplők, helyszínek és utómunka a közösen meghatározott ötlethez igazodnak. || Both HIPStudio’s film page and company profile mention music videos. People, locations and post-production follow the agreed idea. || Sowohl Filmseite als auch Firmenprofil von HIPStudio nennen Musikvideos. Personen, Orte und Nachbearbeitung folgen der gemeinsamen Idee.',
'Az egyeztetéshez a zeneszám, az előadói irány, a költségkeret és a tervezett publikáció legyen világos. A zenei és képi jogokat a produkció előtt tisztázni kell. || Bring the track, artistic direction, budget and publishing plan. Music and image rights need to be clarified before production. || Für die Abstimmung sollten Musikstück, künstlerische Richtung, Budget und Veröffentlichung klar sein. Musik- und Bildrechte müssen vor der Produktion geklärt werden.',
'Kész koncepció nélkül is indulhatunk? || Can we start without a finished concept? || Können wir ohne fertiges Konzept beginnen?',
'A filmkészítési folyamat része lehet a közös ötletelés és forgatókönyv. A koncepció kidolgozásának terjedelmét és díját az ajánlatban rögzítjük. || Collaborative ideation and scripting can be part of the filmmaking process. The quote defines the scope and cost of concept development. || Gemeinsame Ideenentwicklung und Drehbuch können Teil der Filmproduktion sein. Umfang und Kosten der Konzeptentwicklung werden im Angebot festgelegt.')
add('event-video','rendezvenyvideo || event-video || eventvideo','Rendezvényvideó || Event video || Eventvideo','film','rendezvenyfotozas-budapest','referencia-videók',
'A rendezvény üzenete filmben is továbbadható. A beszédek, interjúk és hangulati képek arányát az dönti el, kinek és mire készül az anyag. || An event’s message can continue through film. The balance of speeches, interviews and atmosphere depends on the audience and purpose. || Die Botschaft einer Veranstaltung kann durch einen Film weiterwirken. Das Verhältnis von Reden, Interviews und Atmosphäre richtet sich nach Zielgruppe und Zweck.',
'A HIPStudio zenés vagy interjús eseményfilmet is ismertet. A cégbemutató teljes konferenciarögzítést is említ; ennek technikai és átadási terjedelmét külön kell egyeztetni. || HIPStudio describes music-led or interview-based event films. The company profile also mentions full conference recording, with technical and delivery scope to be agreed separately. || HIPStudio beschreibt musikalische oder interviewbasierte Eventfilme. Das Firmenprofil nennt auch vollständige Konferenzaufzeichnungen, deren Technik und Übergabeumfang gesondert geklärt werden.',
'Küldd el a programot, a kiemelt üzeneteket és a tervezett felületeket. A rövid eseményfilm, az interjú és a teljes előadás külön végtermék lehet. || Send the programme, key messages and intended channels. A short event film, an interview and a complete presentation may be separate deliverables. || Sende Programm, Kernbotschaften und geplante Kanäle. Kurzer Eventfilm, Interview und vollständiger Vortrag können separate Ergebnisse sein.',
'A teljes konferenciafelvétel is lehet referencia? || Can a full conference recording be used as a reference? || Kann eine vollständige Konferenzaufzeichnung als Referenz dienen?',
'Csak megfelelő jogosultsággal. A cégbemutató külön jelzi a bizalmas események korlátait; ügyfélnevet és felvételt nem publikálunk automatikusan. || Only with appropriate rights. The company profile notes restrictions for confidential events; client names and footage are not published automatically. || Nur mit entsprechenden Rechten. Das Firmenprofil weist auf Grenzen bei vertraulichen Veranstaltungen hin; Kundennamen und Aufnahmen werden nicht automatisch veröffentlicht.')
EXTRA=SERVICES[start:]
for s in EXTRA:s['secondarySource']=PDF
