# coding: utf-8
"""Editorial HU/EN/DE adaptations of verified public Wix service descriptions.
Fields are parallel by language; no package prices or delivery promises inferred.
"""
LANGS=['hu','en','de']
def tr(text):
    values=text.split(' || ')
    assert len(values)==3,text
    return dict(zip(LANGS,values))
SERVICES=[]
def add(key,slugs,names,cluster,source,reference,intro,result,brief,question,answer):
    SERVICES.append(dict(key=key,slug=tr(slugs),name=tr(names),cluster=cluster,source='https://www.hipstudio.hu/'+source,reference='https://www.hipstudio.hu/'+reference,intro=tr(intro),result=tr(result),brief=tr(brief),question=tr(question),answer=tr(answer)))
add('business','uzleti-portre || business-portraits || businessportraets','Üzleti portré || Business portraits || Businessporträts','portrait','oneletrajz-cv-fotozas-budapest','portrefotozas-galeria',
'Egy szakmai bemutatkozásnak rád kell hasonlítania. Az üzleti portré a személyiségedet és a szerepedet kapcsolja össze, stúdióban vagy a hozzád illő környezetben. || A professional introduction should feel like you. A business portrait brings together your personality and your role, in the studio or in a setting that suits you. || Ein beruflicher Auftritt sollte zu dir passen. Ein Businessporträt verbindet Persönlichkeit und berufliche Rolle, im Studio oder in einem passenden Umfeld.',
'LinkedInre, céges weboldalra és sajtóanyagba szánt, közösen kiválasztott portrék. A komolyabb és közvetlenebb megjelenés között a felhasználási cél segít dönteni. || Portraits selected together for LinkedIn, company websites and press materials. The intended use helps us choose between a formal and a more relaxed approach. || Gemeinsam ausgewählte Porträts für LinkedIn, Unternehmensseiten und Presseunterlagen. Der Verwendungszweck entscheidet über einen formellen oder einen lockeren Stil.',
'Írd meg, milyen szakmai szerepben jelensz meg, és hol használod majd a képeket. Hozz olyan ruhát, amelyben önazonosnak érzed magad; az eltérő képkivágásokat és környezeteket előre érdemes átbeszélni. || Tell us about your professional role and where the images will appear. Choose clothing that feels like you; discuss different crops and settings before the session. || Beschreibe deine berufliche Rolle und die geplanten Einsatzorte der Bilder. Wähle Kleidung, in der du dich wohlfühlst. Bildausschnitte und Umgebungen besprechen wir vorab.',
'Lehet stúdión kívül is fotózni? || Can we shoot outside the studio? || Ist ein Shooting außerhalb des Studios möglich?',
'Igen, a HIPStudio portréoldala stúdiós és kültéri lehetőséget is ismertet. A konkrét helyszínt és a hozzá tartozó feltételeket az egyeztetés rögzíti. || Yes. HIPStudio describes both studio and outdoor portraits. The location and its requirements are agreed during planning. || Ja. HIPStudio beschreibt Porträts im Studio und im Freien. Den Ort und die dazugehörigen Bedingungen klären wir bei der Planung.')
add('cv','oneletrajz-foto || cv-photography || bewerbungsfotos','Önéletrajz-fotó || CV photography || Bewerbungsfotos','portrait','oneletrajz-cv-fotozas-budapest','portrefotozas-galeria',
'Pályakezdőként és tapasztalt szakemberként is fontos, hogy a bemutatkozásod következetes legyen. Egy önéletrajzhoz készült portré letisztultan mutat meg, túlzó beállítások nélkül. || Whether you are starting out or have years of experience, your introduction should be consistent. A portrait for your CV presents you clearly, without an exaggerated pose. || Ob beim Berufseinstieg oder mit langjähriger Erfahrung: Dein Auftritt sollte stimmig sein. Ein Bewerbungsfoto zeigt dich klar und ohne übertriebene Inszenierung.',
'A cél a jelentkezésedhez illő arckép. A képet az önéletrajz formátumával és a szakmai profiloddal együtt érdemes megtervezni, nem különálló díszítőelemként. || The aim is a portrait that fits your application. Plan it alongside your CV layout and professional profile, rather than as an isolated decoration. || Ziel ist ein Porträt, das zu deiner Bewerbung passt. Plane es gemeinsam mit dem Lebenslauf und deinem beruflichen Profil, nicht als separates Schmuckelement.',
'Az egyeztetéshez elég a megpályázott terület és a kép tervezett használata. Teljes önéletrajzot vagy érzékeny személyes adatokat nem szükséges elküldened a fotózási igény leírásához. || To plan the session, tell us your field and the intended use of the photograph. You do not need to send a full CV or sensitive personal information to describe your photography needs. || Für die Planung genügen dein Berufsfeld und der Verwendungszweck. Ein vollständiger Lebenslauf oder sensible persönliche Daten sind für die Beschreibung deines Fotowunsches nicht nötig.',
'Mi történik, ha nem érzem magam fotogénnek? || What if I do not feel photogenic? || Was ist, wenn ich mich nicht fotogen fühle?',
'A fotózás beszélgetéssel indul. A képeket közösen nézzük át, így a kiválasztásnál te is elmondhatod, melyik megjelenéssel tudsz azonosulni. || We begin with a conversation and review the photographs together. You can say which expression feels right for you. || Wir beginnen mit einem Gespräch und sehen die Bilder gemeinsam durch. Du kannst sagen, mit welchem Ausdruck du dich identifizierst.')
add('headshot','headshot || headshots || headshots','Headshot || Headshots || Headshots','portrait','oneletrajz-cv-fotozas-budapest','reklamfoto-galeria',
'Kis profilképen is felismerhető, közvetlen jelenlét. A headshot az arcra és a tekintetre összpontosít, ezért más képi döntéseket kíván, mint egy teljes alakos portré. || A recognisable, approachable presence even in a small profile image. A headshot focuses on your face and expression, calling for different choices than a full-length portrait. || Auch als kleines Profilbild erkennbar und nahbar. Ein Headshot konzentriert sich auf Gesicht und Ausdruck und verlangt andere Bildentscheidungen als ein Ganzkörperporträt.',
'Olyan arckép a cél, amely kis méretben sem veszíti el a karakterét. A HIPStudio reklámgalériája headshot referenciákat is felsorol; a portréfolyamat közös képkiválasztásra épül. || The goal is a portrait that retains its character at a small size. HIPStudio lists headshots in its commercial gallery and describes a portrait process with joint image selection. || Ziel ist ein Porträt, das auch im kleinen Format seinen Charakter behält. HIPStudio führt Headshots in der Werbegalerie und beschreibt eine gemeinsame Bildauswahl.',
'Hozd el a felület képarányát és arculati elvárásait, ha vannak. Kör alakú profilképnél különösen fontos az arc körüli hely és a háttér viszonya. || Bring the required aspect ratio and any brand guidelines. For a circular profile image, space around the face and the background are particularly important. || Bringe das benötigte Seitenverhältnis und gegebenenfalls Gestaltungsrichtlinien mit. Bei runden Profilbildern sind der Raum um das Gesicht und der Hintergrund besonders wichtig.',
'Miben különbözik az üzleti portrétól? || How does this differ from a business portrait? || Wie unterscheidet sich das vom Businessporträt?',
'A headshot szűkebben az arcra épít. Az üzleti portré több környezetet, testtartást vagy szakmai kontextust is megmutathat. A kívánt képtípust a felhasználás szerint egyeztetjük. || A headshot concentrates more closely on the face. A business portrait may include more setting, posture or professional context. We choose the image type around its intended use. || Ein Headshot konzentriert sich stärker auf das Gesicht. Ein Businessporträt kann mehr Umgebung, Körperhaltung oder beruflichen Kontext zeigen. Die Bildart richtet sich nach dem Verwendungszweck.')
add('dating','tarskereso-fotozas || dating-photos || dating-fotos','Társkereső-fotózás || Dating photography || Dating-Fotografie','portrait','portfolio-fotozas-budapest','portfolio-fotozas-galeria',
'Egy profilképen is önmagadat szeretnéd viszontlátni. A társkereső-fotózás közvetlenebb, hétköznapibb képekből indul ki, és teret hagy a személyiségednek. || You want to recognise yourself in your profile photographs. Dating photography starts with a natural, everyday approach and makes room for your personality. || Auch auf Profilfotos möchtest du dich wiedererkennen. Dating-Fotografie setzt auf eine natürliche, alltagsnahe Darstellung und lässt Raum für deine Persönlichkeit.',
'Változatos, egymással összhangban álló képek készülhetnek stúdióban és kültéren. A cél nem egy idegen szerep felvétele, hanem egy olyan sorozat, amellyel szívesen mutatkozol be. || A varied, coherent series can be created in the studio and outdoors. The aim is a set of photographs you feel comfortable using to introduce yourself. || Eine abwechslungsreiche, zusammenhängende Serie kann im Studio und im Freien entstehen. Ziel sind Bilder, mit denen du dich gerne vorstellst.',
'Gondold át, milyen ruhák és helyzetek jellemzők rád. Az előzetes beszélgetésben a hangulatot, a helyszínt és a ruhaváltásokat is össze tudjuk hangolni. || Think about the clothes and settings that feel like you. During the initial conversation we can align the mood, locations and outfit changes. || Überlege, welche Kleidung und Situationen zu dir passen. Im Vorgespräch stimmen wir Stimmung, Orte und Kleidungswechsel aufeinander ab.',
'Lehet több öltözékben fotózni? || Can I use more than one outfit? || Sind mehrere Outfits möglich?',
'A Wix társkereső- és portfólióoldala több ruhaszettet is ismertet. A választott összeállításokat és a sorozat terjedelmét az aktuális ajánlatban kell rögzíteni. || The Wix dating and portfolio page describes multiple outfits. The selection and scope of your session need to be confirmed in the current quote. || Die Wix-Seite für Dating- und Portfoliofotos beschreibt mehrere Outfits. Auswahl und Umfang werden im aktuellen Angebot festgehalten.')
add('portfolio','portfolio-fotozas || portfolio-photography || portfoliofotografie','Portfólió-fotózás || Portfolio photography || Portfoliofotografie','portrait','portfolio-fotozas-budapest','portfolio-fotozas-galeria',
'Egyetlen kép helyett több oldaladat szeretnéd megmutatni. A portfólió különböző hangulatokat, öltözékeket és képtípusokat fog össze egy személyes sorozattá. || You want to show more than one side of yourself. A portfolio brings together different moods, outfits and image types in a personal series. || Du möchtest mehr als eine Seite von dir zeigen. Ein Portfolio verbindet unterschiedliche Stimmungen, Outfits und Bildarten zu einer persönlichen Serie.',
'A HIPStudio portfóliófolyamata közös koncepcióra, stúdiós vagy külső helyszínre és képkiválasztásra épül. A sorozatot a saját célodhoz érdemes igazítani, legyen az személyes bemutatkozás vagy alkotói anyag. || HIPStudio describes a shared concept, studio or location photography and joint image selection. Shape the series around your own purpose, from a personal introduction to a creative portfolio. || HIPStudio beschreibt ein gemeinsames Konzept, Aufnahmen im Studio oder vor Ort und eine gemeinsame Bildauswahl. Die Serie richtet sich nach deinem Ziel, vom persönlichen Auftritt bis zum kreativen Portfolio.',
'Az inspirációk mellé írd meg azt is, mit nem szeretnél. A helyszínek és öltözékek száma, a smink és a haj igénye mind az előkészítés része. || Alongside inspiration, tell us what you do not want. Locations, outfit changes and any makeup or hair requirements belong in the planning stage. || Nenne neben Inspirationen auch, was du nicht möchtest. Orte, Outfits sowie Wünsche zu Make-up und Haaren gehören zur Vorbereitung.',
'Kérhető smink vagy fodrász? || Can makeup or hair styling be arranged? || Können Make-up oder Haarstyling organisiert werden?',
'A nyilvános portfólióoldal szerint igény esetén sminkes és fodrász is biztosítható. Az elérhetőséget és a díjat az adott fotózáshoz külön egyeztetjük. || The public portfolio page says makeup and hair professionals can be arranged on request. Availability and cost are agreed for the individual session. || Laut öffentlicher Portfolioseite können auf Wunsch Make-up und Haarstyling organisiert werden. Verfügbarkeit und Kosten werden für das jeweilige Shooting geklärt.')
add('fashion','divatfotozas || fashion-photography || modefotografie','Divatfotózás || Fashion photography || Modefotografie','commercial','portfolio-fotozas-budapest','portfolio-fotozas-galeria',
'A ruhának és az embernek ugyanabban a képben kell érvényesülnie. A divatfotózásnál a mozdulat, az anyag és a hangulat együtt alakítja a sorozatot. || The clothing and the person need to work together in the image. In fashion photography, movement, fabric and mood shape the series. || Kleidung und Mensch sollen im selben Bild zur Geltung kommen. Bewegung, Material und Stimmung prägen eine Modeserie.',
'A HIPStudio nyilvános portfólió- és divatfotózási kínálata stúdiós és kültéri sorozatot is tartalmaz. A divatgaléria valós képi támpontot ad a megbeszéléshez. || HIPStudio publicly offers portfolio and fashion sessions in the studio and outdoors. Its fashion gallery provides real visual references for the discussion. || HIPStudio bietet Portfolio- und Modeaufnahmen im Studio und im Freien an. Die Modegalerie liefert konkrete Bildreferenzen für die Abstimmung.',
'A ruhadarabok száma mellett a kollekció karakterét és a megjelenés felületét is írd meg. A modell, a styling, a hátterek és a képarányok tisztázása segít egységes sorozatot tervezni. || Include the collection’s character and publishing channels, as well as the number of garments. Models, styling, backgrounds and aspect ratios help define a coherent series. || Beschreibe neben der Anzahl der Kleidungsstücke auch den Charakter der Kollektion und die Veröffentlichungskanäle. Models, Styling, Hintergründe und Seitenverhältnisse helfen bei einer stimmigen Planung.',
'Elég csak a ruhadarabok számát megadni? || Is the garment count enough for a quote? || Genügt die Anzahl der Kleidungsstücke für ein Angebot?',
'Nem minden sorozat azonos feladat. Az öltözékek mellé a tervezett képtípusokat, helyszínt és felhasználást is add meg, hogy az ajánlat a tényleges produkcióról szóljon. || Each series is different. Include the image types, location and intended use so that the quote reflects the actual production. || Jede Serie ist anders. Ergänze Bildarten, Ort und Verwendungszweck, damit das Angebot die tatsächliche Produktion abbildet.')
add('advertising','reklamfotozas || advertising-photography || werbefotografie','Reklámfotózás || Advertising photography || Werbefotografie','commercial','reklam-fotozas-budapest','reklamfoto-galeria',
'A kampány képeinek világosan kell megmutatniuk, miért fontos a termék vagy a szolgáltatás. A reklámfotózás a kívánt üzenetből és a célközönségből indul ki. || Campaign imagery needs to make the product or service relevant. Advertising photography begins with the message and its intended audience. || Kampagnenbilder sollen die Bedeutung eines Produkts oder einer Leistung vermitteln. Werbefotografie beginnt mit Botschaft und Zielgruppe.',
'A HIPStudio stúdióban és külső helyszínen is készít reklámképeket, szükség esetén mobil műteremmel. A publikus szolgáltatásleírás színhelyes, korrigált, nyomdai felhasználásra is alkalmas képeket ismertet. || HIPStudio creates advertising images in the studio and on location, with a mobile studio where needed. The public service description includes colour-corrected images suitable for print. || HIPStudio erstellt Werbeaufnahmen im Studio und vor Ort, bei Bedarf mit mobilem Studio. Die öffentliche Leistungsbeschreibung nennt farbkorrigierte, auch für Druck geeignete Bilder.',
'A briefben szerepeljen a termék, a célközönség, a megjelenési felület és a kívánt üzenet. Kellékek, szereplők és helyszínek esetén a produkciós igényt is külön írjuk körül. || Include the product, audience, channels and intended message in the brief. Props, people and locations also need a clearly defined production scope. || Das Briefing sollte Produkt, Zielgruppe, Kanäle und Botschaft enthalten. Requisiten, Personen und Drehorte brauchen ebenfalls einen klar definierten Produktionsumfang.',
'Van egységes reklámfotózási ár? || Is there one standard advertising rate? || Gibt es einen einheitlichen Preis für Werbefotografie?',
'A Wix szolgáltatásoldala egyedi árazást ír le. Az árhoz a koncepció, a szükséges technika, a stáb és a felhasználás részletei kellenek. || The Wix service page describes individual pricing. A quote requires the concept, equipment, crew and usage details. || Die Wix-Leistungsseite beschreibt individuelle Preise. Für ein Angebot werden Konzept, Technik, Team und Nutzungsdetails benötigt.')
add('product','termekfotozas || product-photography || produktfotografie','Termékfotózás || Product photography || Produktfotografie','commercial','reklam-fotozas-budapest','reklamfoto-galeria',
'Anyag, felület, részlet: a termékfotó ott ad információt, ahol a leírás önmagában kevés. A képsorozatot a termék jellemzőihez és a megjelenési felülethez kell igazítani. || Material, surface and detail: product photographs provide information that words alone cannot. The series needs to fit both the product and its publishing context. || Material, Oberfläche und Detail: Produktbilder vermitteln Informationen, die Worte allein nicht zeigen. Die Serie muss zum Produkt und zum Einsatzort passen.',
'A termékfotózás a HIPStudio kreatív reklámfotózási körének része. A megvilágítás és a színkorrekció célja, hogy a tárgy érthetően jelenjen meg a kész képen. || Product photography is part of HIPStudio’s commercial photography offering. Lighting and colour correction help present the object clearly. || Produktfotografie gehört zum Werbefotografie-Angebot von HIPStudio. Beleuchtung und Farbkorrektur helfen, den Gegenstand verständlich darzustellen.',
'A darabszám mellett add meg a termékek méretét, anyagát és a kért nézeteket. Az átlátszó, fényes vagy különösen nagy tárgy más előkészítést igényelhet; ezt az ajánlat előtt tisztázzuk. || Include product dimensions, materials and required views, not just the item count. Transparent, reflective or very large objects may need different preparation, which we discuss before quoting. || Nenne neben der Stückzahl auch Maße, Materialien und benötigte Ansichten. Transparente, glänzende oder sehr große Gegenstände können andere Vorbereitungen erfordern; das klären wir vor dem Angebot.',
'Mitől függ a termékfotók mennyisége? || How is the number of product images determined? || Wovon hängt die Anzahl der Produktbilder ab?',
'A termékek száma és a kért nézetek együtt határozzák meg a feladatot. A részletfotókat és a környezetbe helyezett képeket külön is érdemes felsorolni. || The item count and requested views together define the scope. List detail images and photographs showing the product in context separately. || Stückzahl und gewünschte Ansichten bestimmen gemeinsam den Umfang. Detailbilder und Aufnahmen im Anwendungskontext sollten separat aufgeführt werden.')
add('catalogue','katalogusfotozas || catalogue-photography || katalogfotografie','Katalógusfotózás || Catalogue photography || Katalogfotografie','commercial','reklam-fotozas-budapest','reklamfoto-galeria',
'Egy katalógusban a képek egymáshoz való viszonya is számít. Az ismétlődő nézetek, a következetes háttér és a részletek ritmusa segít összehasonlíthatóvá tenni a kínálatot. || In a catalogue, the relationship between images matters. Repeated views, consistent backgrounds and a clear rhythm of detail help readers compare products. || In einem Katalog zählt auch das Verhältnis der Bilder zueinander. Wiederkehrende Ansichten, einheitliche Hintergründe und klare Details erleichtern den Vergleich.',
'A HIPStudio reklámfotózási oldala katalóguscélú munkát is ismertet. Az egységes sorozatot a tördelés és az arculat követelményeivel együtt érdemes előkészíteni. || HIPStudio’s advertising page also describes catalogue work. Prepare a consistent series alongside layout and brand requirements. || Die Werbefotografie-Seite von HIPStudio beschreibt auch Katalogarbeiten. Eine einheitliche Serie sollte gemeinsam mit Layout- und Markenanforderungen vorbereitet werden.',
'A brief része legyen a tétellista, a mintakép, a háttér és a végső képarány. Ha később bővül a katalógus, az új képek illeszkedésének igényét is jelezd. || Include the item list, a sample image, background and final aspect ratio. If the catalogue will grow, mention the need to match later photographs. || Zum Briefing gehören Artikelliste, Musterbild, Hintergrund und endgültiges Seitenverhältnis. Wenn der Katalog erweitert wird, sollte auch die spätere Bildanpassung eingeplant werden.',
'Nyomtatott katalógushoz is kérhető kép? || Can images be prepared for a printed catalogue? || Sind Bilder für gedruckte Kataloge möglich?',
'A nyilvános reklámfotózási leírás nyomdai felbontást és színkorrekciót is említ. A pontos méretet és a nyomdai leadási követelményeket a megrendelés előtt egyeztetni kell. || The public advertising description mentions print resolution and colour correction. Exact dimensions and printer requirements need to be agreed before the commission. || Die öffentliche Beschreibung nennt Druckauflösung und Farbkorrektur. Genaue Maße und Druckvorgaben müssen vor dem Auftrag abgestimmt werden.')
add('property','ingatlanfotozas || property-photography || immobilienfotografie','Ingatlan- és enteriőrfotózás || Property and interior photography || Immobilien- und Interieurfotografie','space','ingatlanfotozas','epulet-fotozas-galeria',
'Egy tér nem csak helyiségek felsorolása. Az ingatlanfotózás az arányokat, a fényt és az egymáshoz kapcsolódó tereket teszi láthatóvá. || A space is more than a list of rooms. Property photography makes proportions, light and connections between spaces visible. || Ein Raum ist mehr als eine Liste von Zimmern. Immobilienfotografie macht Proportionen, Licht und räumliche Zusammenhänge sichtbar.',
'A HIPStudio lakó- és üzleti ingatlanok, épületek és enteriőrök fotózását is ismerteti. A galéria külső épületképeket és belső tereket egyaránt bemutat. || HIPStudio describes photography for residential and commercial properties, buildings and interiors. Its gallery includes both exteriors and interior spaces. || HIPStudio beschreibt Aufnahmen von Wohn- und Gewerbeimmobilien, Gebäuden und Innenräumen. Die Galerie zeigt Außenansichten und Interieurs.',
'Küldd el a helyszínt, a fotózandó terek listáját és a tervezett felhasználást. A hozzáférést, a berendezést és a fotózás időpontját a kívánt fényviszonyokkal együtt érdemes megtervezni. || Send the location, a list of spaces and the intended use. Plan access, furnishings and timing alongside the desired lighting conditions. || Schicke den Standort, eine Liste der Räume und den Verwendungszweck. Zugang, Einrichtung und Termin sollten gemeinsam mit dem gewünschten Licht geplant werden.',
'Belső és külső képek is készülhetnek? || Can the project include interiors and exteriors? || Sind Innen- und Außenaufnahmen möglich?',
'Igen, az ingatlanfotózási szolgáltatás mindkettőt tartalmazhatja. Légi felvétel és 3D séta külön egyeztetendő feladat. || Yes, property photography can cover both. Aerial footage and 3D tours are separate elements to discuss. || Ja, die Immobilienfotografie kann beides umfassen. Luftaufnahmen und 3D-Rundgänge werden gesondert abgestimmt.')
add('aerial','legi-felvetelek || aerial-photography || luftaufnahmen','Légi felvételek || Aerial photography || Luftaufnahmen','space','ingatlanfotozas','epulet-fotozas-galeria',
'Az épület környezete néha csak távolabbról érthető. A légi nézőpont a telek, a megközelítés és a környező terek viszonyát is megmutathatja. || A building’s setting sometimes needs a wider view. An aerial perspective can show the plot, access routes and surrounding spaces. || Die Umgebung eines Gebäudes wird manchmal erst aus größerer Distanz verständlich. Luftaufnahmen können Grundstück, Zufahrt und umliegende Räume zeigen.',
'A HIPStudio ingatlanoldala légi felvételt beltéri fotózáshoz kapcsoltan és önálló megrendelésként is felsorol. A megvalósíthatóságot minden helyszínnél külön kell tisztázni. || HIPStudio’s property page lists aerial photography both alongside interior work and as a separate commission. Feasibility needs to be checked for each location. || Die Immobilienseite von HIPStudio nennt Luftaufnahmen sowohl ergänzend zu Innenaufnahmen als auch als eigenen Auftrag. Die Machbarkeit muss für jeden Ort geklärt werden.',
'Az első egyeztetéshez pontos helyszín és kívánt látószög szükséges. Az időjárás, a helyszíni hozzáférés és az engedélyezési feltételek tisztázása nélkül nem ígérünk konkrét felvételt. || Provide the exact location and desired viewpoints. Specific shots cannot be promised before weather, access and permission requirements have been considered. || Nenne den genauen Ort und gewünschte Perspektiven. Konkrete Aufnahmen können erst nach Klärung von Wetter, Zugang und Genehmigungsvoraussetzungen zugesagt werden.',
'Minden helyszínen elérhető a légi felvétel? || Is aerial photography possible everywhere? || Sind Luftaufnahmen überall möglich?',
'Ez a helyszíni és engedélyezési feltételektől függ. A nyilvános szolgáltatásleírás nem helyettesíti az adott felvétel megvalósíthatóságának ellenőrzését. || It depends on local conditions and permissions. The public service description does not replace a feasibility check for the actual shoot. || Das hängt von örtlichen Bedingungen und Genehmigungen ab. Die öffentliche Leistungsbeschreibung ersetzt keine Machbarkeitsprüfung für die konkrete Aufnahme.')
add('virtual','virtualis-seta || virtual-tours || virtuelle-rundgaenge','3D virtuális séta || 3D virtual tours || Virtuelle 3D-Rundgänge','space','ingatlanfotozas','ingatlanfotozas',
'Ha a látogatónak a helyiségek kapcsolatát is meg kell értenie, a fotók mellé bejárható bemutató adhat további támpontot. || When visitors need to understand how rooms connect, an interactive tour can add context beyond still photographs. || Wenn Besucher die Verbindung zwischen Räumen verstehen sollen, kann ein begehbarer Rundgang die Fotos ergänzen.',
'A HIPStudio nyilvános ingatlanoldalán működő Matterport-referencia szerepel. A 3D séta külön linkként vagy beilleszthető bemutatóként használható, a célfelülettel egyeztetett módon. || HIPStudio’s public property page links to a Matterport reference. A 3D tour can be shared as a link or embedded, subject to the destination platform’s requirements. || Die öffentliche Immobilienseite von HIPStudio verlinkt eine Matterport-Referenz. Ein 3D-Rundgang kann als Link oder eingebettet genutzt werden, abgestimmt auf die Zielplattform.',
'Add meg a bejárandó területet, a hozzáférést és a bemutató célját. A tárhelyet, a hozzáférési időt és a külső szolgáltató feltételeit külön kell tisztázni. || Specify the area to capture, access arrangements and the tour’s purpose. Hosting, access duration and third-party terms need separate agreement. || Beschreibe die zu erfassende Fläche, den Zugang und den Zweck des Rundgangs. Hosting, Zugriffsdauer und Bedingungen des Drittanbieters müssen gesondert geklärt werden.',
'Automatikusan elindul a 3D bemutató az oldalon? || Does the 3D tour load automatically here? || Wird der 3D-Rundgang hier automatisch geladen?',
'Nem. A referenciát külső hivatkozás nyitja meg; a bemutató szolgáltatója csak a link követése után töltődik be. || No. The reference opens through an external link; its provider loads only when you follow that link. || Nein. Die Referenz wird über einen externen Link geöffnet. Der Anbieter wird erst nach dem Aufruf dieses Links geladen.')
add('nude','muveszi-akt || fine-art-nude || kuenstlerischer-akt','Művészi aktfotózás || Fine-art nude photography || Künstlerische Aktfotografie','art','muveszi-aktfotozas-budapest','muveszi-aktfotozas-galeria',
'A művészi akt személyes bizalomra épül. A képek előtt a határokról, az elképzelésekről és arról beszélgetünk, milyen helyzetben tudsz önmagad lenni. || Fine-art nude photography begins with trust. Before photographs, the conversation is about boundaries, ideas and the setting in which you can feel yourself. || Künstlerische Aktfotografie beginnt mit Vertrauen. Vor den Bildern sprechen wir über Grenzen, Vorstellungen und die Situation, in der du dich wohlfühlst.',
'Speier Vikó nyilvános szolgáltatásleírása előzetes beszélgetést, közös tervezést és képkiválasztást ismertet. A hangsúly a személyes, kifejező képeken van. || Speier Vikó’s public service description includes an initial conversation, shared planning and joint image selection. The emphasis is on personal, expressive images. || Die öffentliche Leistungsbeschreibung von Speier Vikó umfasst Vorgespräch, gemeinsame Planung und Bildauswahl. Im Mittelpunkt stehen persönliche, ausdrucksstarke Bilder.',
'A stílust, a ruhákat, a kiegészítőket és a helyszínt előre átbeszéljük. Intim fotót nem szükséges egy első megkereséshez küldened. A nyilvános felhasználás feltételei külön megállapodást igényelnek. || We discuss style, clothing, accessories and location beforehand. You do not need to send intimate photographs with an initial enquiry. Public use requires a separate agreement on its terms. || Stil, Kleidung, Accessoires und Ort besprechen wir vorher. Für eine erste Anfrage brauchst du keine intimen Fotos zu senden. Die öffentliche Nutzung erfordert eine gesonderte Vereinbarung.',
'A fotózás automatikusan portfólió-hozzájárulás? || Does taking part automatically permit portfolio use? || Erlaubt die Teilnahme automatisch eine Portfolionutzung?',
'Nem. A HIPStudio impresszuma külön kezeli a szolgáltatás teljesítését és a referencia- vagy marketingcélú felhasználás megfelelő jogalapját. || No. HIPStudio’s notice distinguishes delivering the service from having an appropriate basis for reference or marketing use. || Nein. Die Datenschutzhinweise von HIPStudio unterscheiden zwischen Leistungserbringung und einer geeigneten Grundlage für Referenz- oder Marketingnutzung.')
add('boudoir','glamour-boudoir || glamour-boudoir || glamour-boudoir','Glamour és boudoir || Glamour and boudoir || Glamour und Boudoir','art','muveszi-aktfotozas-budapest','muveszi-aktfotozas-galeria',
'A finom gesztus, a ruha és a fény együtt adja a boudoir képek hangulatát. Az előzetes beszélgetésben azt keressük, milyen megjelenés áll közel hozzád. || Gesture, clothing and light create the mood of boudoir photographs. The first conversation explores the kind of expression that feels right for you. || Geste, Kleidung und Licht bestimmen die Stimmung von Boudoirbildern. Im ersten Gespräch erkunden wir, welcher Ausdruck zu dir passt.',
'A nyilvános HIPStudio-kínálat a glamour és boudoir fotózást a művészi akttól külön csomagként is bemutatja. A közös tervezés és a személyes határok tisztelete itt is alapvető. || HIPStudio presents glamour and boudoir separately from fine-art nude photography. Shared planning and respect for personal boundaries remain central. || HIPStudio führt Glamour und Boudoir getrennt von künstlerischer Aktfotografie. Gemeinsame Planung und der respektvolle Umgang mit persönlichen Grenzen bleiben zentral.',
'Beszéljük át a ruhákat, a takarás mértékét, a hangulatot és a képek célját. A galéria inspiráció lehet, de nem írja elő, hogyan kell megjelenned. || Discuss clothing, coverage, mood and the purpose of the images. The gallery can be inspiration, but it does not dictate how you should appear. || Wir besprechen Kleidung, Bedeckung, Stimmung und Bildzweck. Die Galerie kann inspirieren, schreibt dir aber keinen bestimmten Auftritt vor.',
'Kell teljes aktot vállalni? || Is full nudity required? || Sind vollständige Aktaufnahmen erforderlich?',
'A glamour/boudoir kínálat fehérneműs képeket is ismertet. A kívánt megjelenést és a határokat az egyeztetésen rögzítjük; az akt külön képi irány. || The glamour and boudoir offering includes lingerie photographs. The intended look and boundaries are discussed; nude work is a separate direction. || Das Glamour- und Boudoirangebot umfasst auch Dessousaufnahmen. Darstellung und Grenzen werden besprochen; Aktaufnahmen sind eine eigene Richtung.')
add('event','rendezvenyfotozas || event-photography || eventfotografie','Rendezvényfotózás || Event photography || Eventfotografie','event','rendezvenyfotozas-budapest','referencia-videók',
'Egy rendezvény nem ismételhető meg a kamera kedvéért. A fotós munkáját a programhoz, a szervezőkhöz és a párhuzamos történésekhez kell igazítani. || An event cannot be repeated for the camera. Photography needs to follow the programme, the organisers and simultaneous activity. || Eine Veranstaltung lässt sich nicht für die Kamera wiederholen. Die Fotografie muss sich am Programm, den Organisatoren und parallelen Abläufen orientieren.',
'A HIPStudio a szervezői csapat részeként írja le a rendezvényfotós munkát. Igény esetén mobil műterem, sajtófal előtti portré és eseményvideó is kapcsolódhat hozzá. || HIPStudio describes its event photographers as working with the organising team. A mobile studio, portraits at a press wall and event video can be discussed as additional elements. || HIPStudio beschreibt die Zusammenarbeit der Eventfotografen mit dem Organisationsteam. Mobiles Studio, Porträts an der Pressewand und Eventvideo können ergänzend abgestimmt werden.',
'A program mellett jelöld meg a fontos szereplőket, a párhuzamos helyszíneket és azokat a pillanatokat, amelyekről mindenképpen szükség van képre. A gyors sajtóválogatás igényét előre jelezd. || Alongside the programme, identify key people, parallel locations and essential moments. Mention any need for a fast press selection in advance. || Nenne neben dem Programm wichtige Personen, parallele Orte und unverzichtbare Momente. Einen Bedarf an schneller Presseauswahl solltest du vorher angeben.',
'Kaphatunk képet már a rendezvény alatt? || Can we receive images during the event? || Können Bilder schon während der Veranstaltung bereitstehen?',
'A Wix leírás szerint igény esetén néhány kép utómunkája rögtön elvégezhető. Ez előzetesen egyeztetendő lehetőség, nem minden megrendelés automatikus határideje. || Wix describes the option of immediate editing for selected images on request. This needs advance agreement and is not an automatic deadline for every commission. || Wix beschreibt auf Wunsch eine zeitnahe Bearbeitung ausgewählter Bilder. Das muss vorher vereinbart werden und ist keine automatische Zusage für jeden Auftrag.')
add('video','videokeszites || video-production || videoproduktion','Videókészítés és reklámfilm || Video and commercial production || Video- und Werbefilmproduktion','film','rovidfilm-keszites','referencia-videók',
'Előbb a mondanivaló, utána a film hossza. A videó akkor tervezhető jól, ha világos, kihez szól, és mit szeretnél megmutatni vele. || The message comes before the running time. Video can be planned well when its audience and purpose are clear. || Die Botschaft kommt vor der Filmlänge. Ein Video lässt sich gut planen, wenn Zielgruppe und Zweck klar sind.',
'A HIPStudio nyilvános folyamata a koncepciótól és forgatókönyvtől a szervezésen át a felvételig és utómunkáig tart. Reklámfilm, image film, interjú és eseményfilm is szerepel a kínálatban. || HIPStudio’s public workflow covers concept, script, organisation, recording and post-production. Its offering includes commercials, image films, interviews and event films. || Der öffentliche Ablauf von HIPStudio reicht von Konzept und Drehbuch über Organisation und Aufnahme bis zur Nachbearbeitung. Zum Angebot gehören Werbe-, Image-, Interview- und Eventfilme.',
'Írd meg az üzenetet, a tervezett közönséget és a közzétételi felületeket. A szereplők, helyszínek, kellékek és a rendelkezésre álló költségkeret segítenek megtervezni a produkciót. || Describe the message, audience and publishing channels. People, locations, props and the available budget help define the production. || Beschreibe Botschaft, Zielgruppe und Veröffentlichungskanäle. Personen, Orte, Requisiten und das verfügbare Budget helfen bei der Produktionsplanung.',
'A rövidebb film mindig kevesebbe kerül? || Is a shorter film always cheaper? || Ist ein kürzerer Film immer günstiger?',
'Nem feltétlenül. A Wix leírása is kiemeli, hogy a rövid, feszesen vágott film elkészítése hasonló munkát igényelhet, mint egy hosszabb anyagé. A tartalom és a produkciós igény számít. || Not necessarily. Wix notes that a short, tightly edited film can require similar work to a longer one. Content and production requirements matter. || Nicht unbedingt. Wix weist darauf hin, dass ein kurzer, straff geschnittener Film ähnlich viel Arbeit erfordern kann wie ein längerer. Inhalt und Produktionsaufwand sind entscheidend.')
add('shoot','forgatas || filming || dreharbeiten','Forgatás || Filming || Dreharbeiten','film','rovidfilm-keszites','referencia-videók',
'A jó forgatási nap az előkészítésen múlik. A szereplők, helyszínek és jelenetek összehangolása teremti meg a használható felvételek feltételeit. || A productive filming day depends on preparation. Aligning people, locations and scenes creates the conditions for useful footage. || Ein erfolgreicher Drehtag hängt von der Vorbereitung ab. Personen, Orte und Szenen müssen aufeinander abgestimmt sein.',
'A HIPStudio filmkészítési folyamata helyszín- és szereplőválasztást, szervezést és operatőri megvalósítást ismertet. A forgatás a közösen meghatározott koncepció része. || HIPStudio describes location and participant selection, production planning and camera work as part of its filmmaking process. Filming follows the agreed concept. || HIPStudio beschreibt Orts- und Personenauswahl, Organisation und Kameraarbeit als Teile der Filmproduktion. Der Dreh folgt dem gemeinsam festgelegten Konzept.',
'A jelenetlista mellett a rendelkezésre álló idősávokat, helyszíni kapcsolatot és technikai kötöttségeket is érdemes összegyűjteni. Nyersanyag-átadásról vagy kizárólag felvételi megbízásról külön kell megállapodni. || Gather the scene list, available time slots, location contact and technical constraints. Raw footage delivery or recording-only assignments require separate agreement. || Sammle Szenenliste, verfügbare Zeitfenster, Kontakt vor Ort und technische Vorgaben. Rohmaterialübergabe oder reine Aufnahmeaufträge erfordern eine gesonderte Vereinbarung.',
'Benne van az utómunka a forgatásban? || Does filming include post-production? || Ist die Nachbearbeitung im Dreh enthalten?',
'A teljes filmkészítési folyamat tartalmaz utómunkát, de a konkrét megrendelés terjedelmét az ajánlat rögzíti. A forgatási nap önmagában nem határozza meg a kész filmek számát. || The complete filmmaking process includes post-production, but the quote defines your commission’s scope. A filming day alone does not determine the number of finished films. || Der vollständige Filmprozess umfasst Nachbearbeitung; den konkreten Auftragsumfang legt das Angebot fest. Ein Drehtag allein bestimmt nicht die Anzahl fertiger Filme.')
add('werk','werkfilm || behind-the-scenes-films || making-of-filme','Werkfilm és aftermovie || Behind-the-scenes films and aftermovies || Making-of-Filme und Aftermovies','film','rovidfilm-keszites','referencia-videók',
'A történések mögötti munka és az esemény hangulata külön történetet alkot. A werkfilm és az aftermovie ezt a folyamatot sűríti nézhető sorozattá. || The work behind an event and its atmosphere form their own story. Behind-the-scenes films and aftermovies bring that experience into a watchable sequence. || Die Arbeit hinter einem Ereignis und seine Atmosphäre erzählen eine eigene Geschichte. Making-of-Filme und Aftermovies verdichten diese Erfahrung zu einer Bildfolge.',
'A HIPStudio filmoldala zenés werkvideót és aftermovie-t is ismertet; a referenciák között rövid rendezvény werkfilmek szerepelnek. A ritmust a történések és a tervezett közönség alakítja. || HIPStudio describes music-led behind-the-scenes videos and aftermovies, and lists short event films among its references. The activity and intended audience shape the rhythm. || HIPStudio beschreibt musikalisch gestaltete Making-of-Videos und Aftermovies und führt kurze Eventfilme als Referenzen. Geschehen und Zielgruppe bestimmen den Rhythmus.',
'Jelöld meg a kulcspillanatokat, az előkészületekhez való hozzáférést és a kívánt hangulatot. Interjú, zene, felirat és többféle képarány esetén külön egyeztetjük az utómunkát. || Identify key moments, access to preparations and the desired mood. Interviews, music, captions and multiple aspect ratios need specific post-production planning. || Nenne Schlüsselmomente, Zugang zu Vorbereitungen und gewünschte Stimmung. Interviews, Musik, Untertitel und mehrere Seitenverhältnisse erfordern eine eigene Abstimmung der Nachbearbeitung.',
'Lehet interjú is az eseményfilmben? || Can an event film include interviews? || Können Interviews im Eventfilm vorkommen?',
'Igen, a rendezvényoldal zenés vagy interjús film lehetőségét írja le. A megszólalókat, a kérdéseket és a hangfelvétel körülményeit előre érdemes tisztázni. || Yes. The event page describes music-led or interview-based films. Agree speakers, questions and audio recording conditions in advance. || Ja. Die Eventseite beschreibt musikalische oder interviewbasierte Filme. Gesprächspartner, Fragen und Tonbedingungen sollten vorab geklärt werden.')
add('social','social-media-film || social-media-films || social-media-filme','Social-media film || Social media films || Social-Media-Filme','film','rovidfilm-keszites','referencia-videók',
'Rövid felületen is egyértelmű üzenetre van szükség. A közösségi csatornára tervezett filmnél a képarány, a kezdőkép és a néző helyzete is az ötlet része. || A short format still needs a clear message. For social channels, aspect ratio, the opening image and the viewer’s context are part of the idea. || Auch ein kurzes Format braucht eine klare Botschaft. Bei Social-Media-Filmen gehören Seitenverhältnis, Einstiegsbild und Nutzungssituation zur Idee.',
'A HIPStudio nyilvános filmkínálata rövid videókat, vírusvideót és pre-roll szpotot is említ. A csatornához illeszkedő változatokat a koncepcióban érdemes meghatározni. || HIPStudio’s public film offering includes short videos, viral-style videos and pre-roll spots. Channel-specific versions should be defined in the concept. || Das öffentliche Filmangebot von HIPStudio nennt Kurzvideos, virale Videoformate und Pre-Roll-Spots. Kanalspezifische Varianten sollten im Konzept festgelegt werden.',
'Írd meg a platformot, a képarányt, az üzenetet és azt, hogy hang nélkül is érthetőnek kell-e lennie az anyagnak. A feliratok és külön változatok legyenek részei a briefnek. || State the platform, aspect ratio, message and whether the film must work without sound. Include captions and separate versions in the brief. || Nenne Plattform, Seitenverhältnis, Botschaft und ob der Film ohne Ton verständlich sein soll. Untertitel und zusätzliche Versionen gehören ins Briefing.',
'Egy forgatásból több változat is tervezhető? || Can one shoot be planned for several versions? || Lassen sich aus einem Dreh mehrere Versionen planen?',
'Ez a koncepció és a felvett anyag függvénye. A változatokat a forgatás előtt érdemes egyeztetni; utólag nem minden képkivágás vagy tartalmi irány pótolható. || It depends on the concept and footage. Plan versions before filming; not every crop or content direction can be recovered afterwards. || Das hängt von Konzept und Material ab. Varianten sollten vor dem Dreh geplant werden; nicht jeder Ausschnitt oder Inhalt lässt sich nachträglich ergänzen.')
add('podcast','podcast-keszites || podcast-production || podcastproduktion','Podcastkészítés || Podcast production || Podcastproduktion','film','podcast-keszites','podcast-keszites',
'A beszélgetés akkor működik, ha a technika helyett a témára figyelhetsz. A videós podcast a hangot, a személyiséget és a képi jelenlétet kapcsolja össze. || A conversation works best when you can focus on the subject instead of the equipment. A video podcast brings together voice, personality and visual presence. || Ein Gespräch gelingt besser, wenn du dich auf das Thema statt auf die Technik konzentrieren kannst. Ein Videopodcast verbindet Stimme, Persönlichkeit und visuelle Präsenz.',
'A HIPStudio tématervezést, műsorstruktúrát, hang- és videófelvételt, szerkesztést és disztribúciót ismertet. Mobil stúdióval az irodai helyszín lehetőségét is leírja. || HIPStudio describes topic planning, programme structure, audio and video recording, editing and distribution. It also describes recording at an office with a mobile studio. || HIPStudio beschreibt Themenplanung, Sendungsstruktur, Ton- und Videoaufnahme, Schnitt und Distribution. Auch Aufnahmen im Büro mit mobilem Studio werden genannt.',
'Az első briefben a témák, a résztvevők száma, a helyszín és a sorozat célja legyen világos. A publikálási csatornákat és az utómunka terjedelmét külön egyeztetjük. || Start with the subjects, number of participants, location and the series’ purpose. Publishing channels and the scope of editing need separate agreement. || Im ersten Briefing sollten Themen, Teilnehmerzahl, Ort und Ziel der Serie klar sein. Veröffentlichungskanäle und Umfang der Nachbearbeitung werden gesondert abgestimmt.',
'Csak a stúdióban készülhet felvétel? || Is recording limited to the studio? || Sind Aufnahmen nur im Studio möglich?',
'Nem. A publikus podcastoldal mobil stúdiós, irodai felvételt is ismertet. A helyszín alkalmasságát és a technikai feltételeket előzetesen egyeztetjük. || No. The public podcast page describes office recording with a mobile studio. We discuss the location’s suitability and technical requirements beforehand. || Nein. Die öffentliche Podcastseite beschreibt Büroaufnahmen mit mobilem Studio. Eignung des Ortes und technische Voraussetzungen werden vorher geklärt.')
PENDING=[{'service':s,'status':'source_and_content_approval_required','reason':'No separate substantiated offer in captured Wix body content; user-requested scope retained for review.'} for s in ['executive portrait','C-level event photography','brand photography','visual positioning','studio rental','standalone fine-art photography']]
# Secondary source explicitly approved by user for pricing: BANHALMI. These
# are editorially separated applications of its documented service packages.
add('executive','executive-portre || executive-portraits || executive-portraets','Executive portré || Executive portraits || Executive-Porträts','portrait','oneletrajz-cv-fotozas-budapest','portrefotozas-galeria',
'A vezetői portrénak a személyt és a felelősségi kört is hitelesen kell képviselnie. A cél a szakmai szerephez illő, következetes megjelenés. || An executive portrait needs to represent both the person and their responsibility. The aim is a consistent presence that fits the professional role. || Ein Executive-Porträt soll die Person und ihre Verantwortung glaubwürdig darstellen. Ziel ist ein stimmiger Auftritt, der zur beruflichen Rolle passt.',
'Sajtóportré, vezetői bemutatkozás és céges profil eltérő képkivágást igényelhet. Az executive csomagok a felhasználó által kijelölt BANHALMI árazási rendszerből származnak, HIPStudiohoz igazított áfatartalommal. || Press portraits, executive introductions and company profiles may require different crops. Executive packages use the designated BANHALMI pricing framework with HIPStudio’s VAT treatment. || Presseporträts, Führungskräftevorstellungen und Unternehmensprofile können unterschiedliche Ausschnitte benötigen. Die Executive-Pakete nutzen den vorgegebenen BANHALMI-Preisrahmen mit der Umsatzsteuerbehandlung von HIPStudio.',
'Az egyeztetéshez add meg a szerepkört, a vállalati arculati elvárásokat és a publikálási helyeket. A rendelkezésre álló idő és a jóváhagyó személy meghatározása segíti az előkészítést. || Include the role, brand requirements and publishing channels. Knowing the available time and the person approving the images helps with preparation. || Nenne Rolle, Gestaltungsanforderungen und Veröffentlichungskanäle. Verfügbare Zeit und Freigabeverantwortliche helfen bei der Vorbereitung.',
'Készülhet több felületre alkalmas vezetői portré? || Can executive portraits serve several channels? || Können Executive-Porträts für mehrere Kanäle entstehen?',
'Igen, a képkivágásokat és felhasználási célokat előre érdemes meghatározni. A végleges darabszámot és a jogokat az ajánlat rögzíti. || Yes. Define crops and uses in advance. The quote records final image quantities and rights. || Ja. Ausschnitte und Nutzung sollten vorab festgelegt werden. Bildanzahl und Rechte werden im Angebot dokumentiert.')
add('brand','brand-fotozas || brand-photography || brandfotografie','Brand-fotózás || Brand photography || Brandfotografie','commercial','reklam-fotozas-budapest','reklamfoto-galeria',
'Ha a márkád minden felületen más arcot mutat, a képi jelenlétet együtt érdemes megtervezni. A brand-fotózás a szereplőket, a helyszínt és a kommunikáció célját kapcsolja össze. || When a brand looks different on every channel, its visual presence needs a shared plan. Brand photography connects people, setting and communication goals. || Wenn eine Marke auf jedem Kanal anders wirkt, braucht ihr visueller Auftritt einen gemeinsamen Plan. Brandfotografie verbindet Menschen, Umgebung und Kommunikationsziele.',
'A portrék, munkakörnyezetek és részletek együtt alkotnak használható képi készletet. A csomagok a BANHALMI brand- és vizuális pozicionálási szolgáltatásához kapcsolódnak. || Portraits, working environments and details form a useful image collection together. Packages relate to BANHALMI’s brand photography and visual positioning service. || Porträts, Arbeitsumgebungen und Details ergeben gemeinsam einen nutzbaren Bildbestand. Die Pakete beziehen sich auf BANHALMIs Brandfotografie und visuelle Positionierung.',
'Írd össze a szükséges felületeket és azokat az üzeneteket, amelyekhez saját kép kell. Fontos a szereplők száma, a helyszín és a ténylegesen kiválasztandó képek mennyisége. || List the channels and messages that need original imagery. Include participant count, location and the number of final images required. || Liste die Kanäle und Botschaften auf, für die eigene Bilder benötigt werden. Wichtig sind Personenzahl, Ort und Anzahl der final ausgewählten Bilder.',
'A csomagban szereplő képszám személyenként értendő? || Is the included image count per person? || Gilt die enthaltene Bildanzahl pro Person?',
'A BANHALMI brand csomagjaiban a három retusált kép projektenként értendő. A további kiválasztott képek külön tételt jelentenek. || BANHALMI brand packages include three retouched images per project. Additional selected images are separate items. || Die BANHALMI-Brandpakete enthalten drei retuschierte Bilder pro Projekt. Weitere ausgewählte Bilder sind separate Positionen.')
add('positioning','vizualis-pozicionalas || visual-positioning || visuelle-positionierung','Vizuális pozicionálás || Visual positioning || Visuelle Positionierung','commercial','reklam-fotozas-budapest','reklamfoto-galeria',
'Mit szeretnél, hogy megértsenek rólad az első képből? A vizuális pozicionálás ezt a kérdést fordítja le a fotózás céljára, stílusára és felhasználására. || What should the first image help people understand about you? Visual positioning translates that question into the purpose, style and use of the photography. || Was sollen Menschen schon durch das erste Bild über dich verstehen? Visuelle Positionierung übersetzt diese Frage in Ziel, Stil und Verwendung der Fotos.',
'A cél a döntések összehangolása: kit szólítasz meg, milyen szerepben jelensz meg, és hol találkoznak a képeiddel. A brand-fotózáshoz kapcsolódó tervezési irányként kezeljük. || The aim is to align the audience, the role you present and the places where your images appear. We treat it as a planning direction within brand photography. || Ziel ist die Abstimmung von Zielgruppe, dargestellter Rolle und Einsatzorten der Bilder. Wir behandeln sie als Planungsansatz innerhalb der Brandfotografie.',
'Hozd el a jelenlegi bemutatkozásodat, a célközönség leírását és néhány képi példát. A vizuális irány nem helyettesít üzleti stratégiát és nem jelent garantált értékesítési eredményt. || Bring your current introduction, an audience description and a few visual examples. Visual direction does not replace business strategy or guarantee sales results. || Bringe deinen aktuellen Auftritt, eine Zielgruppenbeschreibung und einige Bildbeispiele mit. Visuelle Ausrichtung ersetzt keine Unternehmensstrategie und garantiert keine Verkaufsergebnisse.',
'Ez külön tanácsadási díjcsomag? || Is this a separate consulting package? || Ist das ein separates Beratungspaket?',
'A kijelölt árazási forrás közös brand-fotózás és vizuális pozicionálás kategóriát használ. Önálló tanácsadási árat nem állítunk; külön igényhez egyedi ajánlat kell. || The designated pricing source combines brand photography and visual positioning. We do not state a standalone consulting price; separate requirements need a tailored quote. || Die vorgegebene Preisquelle verbindet Brandfotografie und visuelle Positionierung. Ein eigenständiger Beratungspreis wird nicht angegeben; separate Anforderungen benötigen ein individuelles Angebot.')
add('fineart','muveszi-fotozas || fine-art-photography || kuenstlerische-fotografie','Művészi fotózás || Fine-art photography || Künstlerische Fotografie','art','portfolio-fotozas-budapest','portfolio-fotozas-galeria',
'Egy előadói vagy alkotói jelenlétet nem mindig lehet hagyományos profilképbe sűríteni. A művészi fotózás a karakternek, a mozdulatnak és az egyéni képi világnak ad teret. || An artistic presence cannot always fit into a conventional profile image. Fine-art photography makes room for character, movement and a personal visual language. || Eine künstlerische Präsenz passt nicht immer in ein klassisches Profilbild. Künstlerische Fotografie gibt Charakter, Bewegung und einer eigenen Bildsprache Raum.',
'A kijelölt BANHALMI forrás színészi, táncos, előadóművészi, modell- és editorial portfóliót is felsorol. A felhasználás és a saját alkotói irány együtt alakítja az anyagot. || The designated BANHALMI source lists acting, dance, performing arts, modelling and editorial portfolios. Intended use and creative direction shape the work together. || Die vorgegebene BANHALMI-Quelle nennt Schauspiel-, Tanz-, Bühnen-, Model- und Editorial-Portfolios. Verwendungszweck und künstlerische Richtung prägen das Material gemeinsam.',
'Az inspirációk mellett add meg a műfajt és a portfólió célját. Mozgásos felvételnél a térigényt, ruhákat és kellékeket is érdemes előre átbeszélni. || Alongside inspiration, describe your discipline and portfolio purpose. For movement-based work, discuss space, clothing and props in advance. || Nenne neben Inspirationen auch Sparte und Portfolioziel. Bei Bewegungsaufnahmen sollten Platzbedarf, Kleidung und Requisiten vorab besprochen werden.',
'Ez ugyanaz, mint a művészi akt? || Is this the same as fine-art nude photography? || Ist das dasselbe wie künstlerische Aktfotografie?',
'Nem. Ez az alkotói és előadói portfólió iránya. A művészi akt külön szolgáltatás és külön személyes egyeztetés tárgya. || No. This concerns artistic and performance portfolios. Fine-art nude photography is a separate service with its own consultation. || Nein. Hier geht es um künstlerische und darstellerische Portfolios. Aktfotografie ist eine separate Leistung mit eigener Abstimmung.')
add('clevel','c-level-rendezvenyfotozas || c-level-event-photography || c-level-eventfotografie','C-level rendezvényfotózás || C-level event photography || C-Level-Eventfotografie','event','rendezvenyfotozas-budapest','referencia-videók',
'Vezetői találkozón a fontos pillanatok és a protokoll egyszerre határozzák meg a munkát. A fotózási tervnek a programot és a megjelenési elvárásokat is követnie kell. || At a leadership event, key moments and protocol both shape the work. The photography plan needs to reflect the programme and publication requirements. || Bei einer Führungskräfteveranstaltung bestimmen Schlüsselmomente und Protokoll die Arbeit. Der Fotoplan muss Programm und Veröffentlichungsvorgaben berücksichtigen.',
'A kijelölt BANHALMI árazási rendszer külön C-level rendezvénycsomagokat tartalmaz. A helyszínek és párhuzamos programok számához illeszkedő fotósi kapacitást a brief alapján lehet tervezni. || The designated BANHALMI pricing framework includes C-level event packages. Photographer capacity can be planned around locations and parallel sessions in the brief. || Der vorgegebene BANHALMI-Preisrahmen enthält C-Level-Eventpakete. Die Fotografenkapazität richtet sich nach Orten und parallelen Programmpunkten im Briefing.',
'Add meg a vendégszámot, a párhuzamos programokat, a protokolláris kötöttségeket és a képek jóváhagyási útját. Zárt eseménynél a nyilvános felhasználás körét külön tisztázni kell. || Include guest count, simultaneous sessions, protocol and the image approval process. For a closed event, public use must be agreed separately. || Nenne Gästezahl, parallele Programmpunkte, Protokoll und Bildfreigabeprozess. Bei geschlossenen Veranstaltungen muss öffentliche Nutzung gesondert geklärt werden.',
'Mikor szükséges több fotós? || When are additional photographers needed? || Wann werden weitere Fotografen benötigt?',
'Párhuzamos programoknál és nagyobb eseménynél a kapacitást külön tervezzük. A forrás árazási logikája a vendégszámot és a párhuzamos programokat is figyelembe veszi. || Capacity needs separate planning for simultaneous sessions and larger events. The source pricing logic considers guest count and parallel activity. || Bei parallelen Programmpunkten und größeren Veranstaltungen wird die Kapazität gesondert geplant. Die Preislogik der Quelle berücksichtigt Gästezahl und parallele Abläufe.')
for s in SERVICES:
    if s['key'] in ['executive','brand','positioning','fineart','clevel']:
        s['secondarySource']='https://github.com/880rzz/BANHALMI/blob/c3bc1143254a467cb8d47091e84acc2aac361ebc/pricing-huf.json'
PENDING=[{'service':'studio rental','status':'conditions_required','reason':'Wix confirms a studio but no independent rental terms, capacity, equipment list or price. Studio page accepts an enquiry without claiming rental availability.'}]
